#!/bin/sh

set -e

DESTDIR=/usr
datadir=$DESTDIR/share
icondir=$datadir/icons

case "$1" in
    remove)        
        gtk-update-icon-cache -f -t $icondir/ubuntu-mono-light
        gtk-update-icon-cache -f -t $icondir/ubuntu-mono-dark
    ;;

    purge)
    ;;

    upgrade)
    ;;

    failed-upgrade)
    ;;

    abort-install|abort-upgrade)
    ;;

    disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

