#!/bin/bash
#
# NSsbackup service file used by cron/anacron

set -e

if [ -x /usr/bin/nice ]; then
nicecmd="/usr/bin/nice -n 19"
fi

# See ionice(1)
if [ -x /usr/bin/ionice ]; then
#ionicecmd="/usr/bin/ionice -c 2 -n 7 -t"
ionicecmd="/usr/bin/ionice -c 3 -t"
fi

if [ -x /usr/bin/nssbackupd ]; then
$nicecmd $ionicecmd /usr/bin/nssbackupd
elif [ -x /usr/local/bin/nssbackupd ]; then
$nicecmd $ionicecmd /usr/local/bin/nssbackupd
fi
