#!/bin/bash

#
#   NSsbackup service file used by cron/anacron
#   Do not call this file manually.
#
#   Copyright (c)2007: Ouattara Oumar Aziz <wattazoum@gmail.com>
#   Copyright (c)2010: Jean-Peer Lorenz <peer.loz@gmx.net>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


PATH=/usr/local/bin:/usr/bin:/bin

if [ -x /usr/bin/nice ]; then
	nicecmd="/usr/bin/nice -n 19"
fi

# See ionice(1)
if [ -x /usr/bin/ionice ]; then
	#ionicecmd="/usr/bin/ionice -c 2 -n 7 -t"
	# option -t is not implement in Ubuntu Hardy
	ionicecmd="/usr/bin/ionice -c 3"
fi

if [ -x /usr/bin/nssbackupd ]; then
	$nicecmd $ionicecmd /usr/bin/nssbackupd
elif [ -x /usr/local/bin/nssbackupd ]; then
	$nicecmd $ionicecmd /usr/local/bin/nssbackupd
fi
