#!/usr/bin/env python
#
#    Simple Backup - TAR checkpoint action over DBus
#
#   Copyright (c)2010: Jean-Peer Lorenz <peer.loz@gmx.net>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


import os
import dbus


tar_checkpoint_str = os.environ['TAR_CHECKPOINT']

try:
    _system_bus = dbus.SystemBus()
    remote_obj = _system_bus.get_object("org.launchpad.nssbackupService",
                                         "/nssbackupdDbusObject")
except dbus.DBusException, exc:
    remote_obj = None

if remote_obj is not None:
    remote_obj.emit_progress_signal(tar_checkpoint_str,
        dbus_interface = "org.launchpad.nssbackupService.nssbackupdDbusInterface")
